name: CI

on:
  push:
    branches: ["*"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    env:
      ABI: "armeabi-v7a,arm64-v8a,x86,x86_64"
      NDK_VERSION: "28.0.13004108"
      CMAKE_VERSION: "3.31.6"
      ANDROID_PLATFORM: "23"

    steps:
      - name: Install build dependencies
        # android-actions/setup-android needs unzip
        # sdkmanager needs jre
        run: |
          pacman -Syu --needed --noconfirm \
            git unzip jre-openjdk \
            ghc cabal-install haskell-shake haskell-aeson-pretty \
            cmake extra-cmake-modules ninja \
            fmt boost \
            python opencc \
            gperf github-cli

      - name: Fetch source code
        uses: actions/checkout@v4
        with:
          # this only sync submodules specified in .gitmodules,
          # because we don't want recursive submodules in glog, librime, etc.
          submodules: true

      - name: Fetch submodules
        run: |
          # it appears to be a bug when building in containers: https://github.com/actions/checkout/issues/915
          git config --global --add safe.directory '*'
          # fetch nested submodules not listed in the top-level .gitmodules
          git submodule sync --recursive
          git submodule update --init --recursive libime librime-predict-leveldb

      - name: Setup Android NDK
        uses: android-actions/setup-android@v3
        with:
          packages: "ndk;${{ env.NDK_VERSION }} cmake;${{ env.CMAKE_VERSION }}"

      - name: Build everything
        env:
          ANDROID_NDK_ROOT: ${{ env.ANDROID_HOME }}/ndk/${{ env.NDK_VERSION }}
        run: |
          # use archlinux's dynamic only ghc
          cabal configure --disable-library-vanilla --enable-shared --enable-executable-dynamic --ghc-options=-dynamic
          ./build-cabal -j everything

      - name: Pack prebuilt libraries
        run: |
          cd build
          mkdir prebuilt
          for TARGET in $(<artifacts.txt)
          do
            cp -a "$TARGET" prebuilt/
          done
          tar --zstd -cf prebuilt.tar.zst prebuilt/

      - name: Upload prebuilt to artifact
        uses: actions/upload-artifact@v4
        with:
          name: prebuilt-${{ github.run_number }}
          path: build/prebuilt.tar.zst
